language: python

python:
    - 3.5  # not really used, since the anaconda one supercedes it

before_install:

    # UPDATE APT-GET LISTINGS

    - sudo apt-get update

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes

    - export PYTHONIOENCODING=UTF8

    # Install miniconda following instructions at
    # http://conda.pydata.org/docs/travis.html
    
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # DOCUMENTATION DEPENDENCIES
    - if [[ $SETUP_CMD == build_sphinx* ]]; then sudo apt-get install graphviz texlive-latex-extra dvipng; fi

    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:

    - conda env create --quiet --force --name cta-dev --file environment.yml
    - source activate cta-dev
    - ulimit -s 16000  # increase stack size limit, for libhessio

script: make test

after_script:
  - source deactivate

  

